### ISSUE TITLE
Why the OAuth 2.0 superstition ?

### ISSUE THREAD

**Issue by amoldeshpande** [Yelp/yelp-api-v3#10]
- I'm not authorizing any yelp users, just my own developer credentials
- There are no claims/scopes to grant to my app. 

Why in god's name do I have to jump through  OAuth 2.0 hoops when all you need is a token/app id that tells you who the app developer is ? 

Your api is already https, so security of that token should not be an issue.

**Comment by guangyang** [comment]
We may look into providing user information/action in the future. Having one auth mechanism for now and future is the main reason behind using OAuth 2.0.

**Comment by davecom** [comment]
Are you no longer using OAuth 1 because of security concerns? It is much more convenient for the scenario @amoldeshpande highlights - apps where no Yelp users are authorized and only developer credentials are used.

**Comment by amoldeshpande** [comment]
@guangyang , I'm sorry but if you do add user information/action in the future, you will still need to provide an api that's independent of user authentication.  
I can't imagine that you will make me force the user to log in to yelp just to search for nearby businesses, for example.  

Please give this design some more thought.
thanks.

**Comment by guangyang** [comment]
@davecom, it's not about security concern. We do feel OAuth 2.0 is a more proper authentication. Also, OAuth 1.0 isn't really that easy to use since it requires signing the entire request. We've received quite a few questions/issues where people ran into trouble with the signing.

@amoldeshpande, we are definitely not requiring users to log in to Yelp just for search. OAuth 2.0 has a few flows. In particular, we are enabling the client credentials flow right now, which requires no user log in. In the future, if we consider user specific information/action, we can then easily enable the authorization code flow, which requires user login. OAuth 2.0 is nice in this way.

Please take a look at the tutorial at https://github.com/Yelp/yelp-api-v3/blob/master/docs/tutorials/get-start-yelp-api-v3.md. It has instructions of how to authenticate API calls and there is no user login involved. We can certainly call it out in the tutorial and FAQ that it doesn't require user login.

**Comment by amoldeshpande** [comment]
I fully understand what the current flow is.  My point is that the only reason OAuth 2.0 would make sense in the future is if you were to add user login.  

Thanks for the discussion. Closing this issue.
