### ISSUE TITLE
plans to add rating_img_url ?

### ISSUE THREAD

**Issue by amoldeshpande** [Yelp/yelp-api-v3#11]
These used to be available in v1 and v2. Any plans to add them in v3 ? thanks.

**Comment by guangyang** [comment]
You can get them manually following this FAQ https://github.com/Yelp/yelp-api-v3/blob/master/docs/others/faq.md#where-can-i-get-high-resolution-versions-of-the-yelp-stars-and-logos.

The reason we aren't including them in v3 is because we think you'll need different versions/sizes of them based on the platform/device you are building for. So it won't give you the best experience by just returning one URL.

Does this make sense to you?

**Comment by watterso** [comment]
For more relevant thoughts see our response to a similar issue in v2: [yelp-api issue #133](https://github.com/Yelp/yelp-api/issues/133).

**Comment by amoldeshpande** [comment]
cool, thanks.
