### ISSUE TITLE
Search API: location by geographical bounding box

### ISSUE THREAD

**Issue by sp00m** [Yelp/yelp-api-v3#16]
In the search API, specifying the location by geographical bounding box does not seem to be available anymore: what is the reason of this removal? I found it quite convenient when using Google Maps to geolocates businesses for example, as it's easy to get the SW/NE latitudes/longitudes.

**Comment by guangyang** [comment]
The reason it's currently removed is because we feel that lat/long + radius should be able to support the same scenario. In your case, I think you can make the conversion between the two, right? Is that a lot of trouble? Please help us understand. We do want to provide good functionality but keep the interface simple.

**Comment by sp00m** [comment]
Yes, I was planning to use lat/long/rad instead, but it will just cover a little bit more than I need, as phones screens are rectangular... Also, having this conversion calculation factored in your API will avoid all your API consumers to develop it ;) But anyway, trying to keep an interface simple but functional sounds like a good idea, so let's fall back to the lat/long/rad solution!
